#!/bin/bash
exec </dev/tty

###################################################################################################################
## Runs "npm install" and/or "composer install" if their config files where changed and depending on user input. ##
###################################################################################################################

# Color vars
C_RED="\033[31m"
C_GREEN="\033[32m"
C_YELLOW="\033[33m"

# Clear Format
NO_FORMAT="\033[0m"

COUNTER=0
changed_files=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)
install=()

run_config() {
    echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

ask_config() {
    echo -ne "Do you want to run '${C_YELLOW}$*${NO_FORMAT}'? (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) "
    read answer

    while [[ "$answer" != "y" && "$answer" != "n" ]]
    do
        echo -ne "${C_YELLOW}$*${NO_FORMAT}Wrong input. try again. (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) "
        read answer
    done

    if [[ "$answer" == "y" ]]; then
        install+=("$*")
    fi
}

run_config package.json "ask_config ""npm install"" "
run_config composer.json "ask_config ""composer install"" "
# Add here more if needed.

for COMMAND in "${install[@]}"
do
    echo "Running $COMMAND..."
    $COMMAND
    echo "$COMMAND completed!"
done