#!/bin/bash
exec </dev/tty

###########################################################################################
## Deletes the remote and/or local branch that was just merged, depending on user input. ##
###########################################################################################

# Color vars
C_RED="\033[31m"
C_GREEN="\033[32m"

# Background vars
B_BLUE="\033[44m"
B_PURPLE="\033[45m"

# Clear Format
NO_FORMAT="\033[0m"

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")

# Get the name of the branch that was just merged
reflog_message=$(git reflog -1)
merged_branch_name=$(echo $reflog_message | cut -d" " -f 4 | sed "s/://")

# if the merged branch was master - don't do anything
if [[ $merged_branch_name == "master" ]]; then
    exit 0
fi

# Begin output
echo ""
echo "You've just merged the branch \"$merged_branch_name\" into \"$branch_name\". "

# Ask the question
read -p "${B_BLUE}[LOCAL]${NO_FORMAT} Do you want to delete the \"$merged_branch_name\" branch? (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) " answer

# Check if the answer is a single lowercase Y
if [[ "$answer" == "y" ]]; then

    # Delete the local branch
    echo "Deleting local branch \"$merged_branch_name\"..."
    git branch -d $merged_branch_name
else
    echo "Did not delete the \"$merged_branch_name\" branch."
fi

read -p "${B_PURPLE}[REMOTE]${NO_FORMAT} Do you want to delete the \"$merged_branch_name\" branch? (${C_GREEN}y${NO_FORMAT}/${C_RED}n${NO_FORMAT}) " answer

# Check if the answer is a single lowercase Y
if [[ "$answer" == "y" ]]; then
    # Delete the remote branch
    echo "Deleting remote branch \"$merged_branch_name\"..."
    git push origin --delete $merged_branch_name
    exit 1
else
    echo "Did not delete the remote \"$merged_branch_name\" branch."
fi
